### ISSUE TITLE
What is the best prompt-text for the conversation?

### ISSUE THREAD

**Issue by kyleboddy** [orhanerday/ChatGPT#1]
I came here from the openai-api project, which is awesome. I decided to use this as the "Hello World" of the api, and got it working. However, the results are quite lackluster using this project, as evidenced below:

![image](https://user-images.githubusercontent.com/746351/220245652-cb1c41e9-471c-44d5-a431-f3936f339b42.png)

ChatGPT gives vibrant answers to all the questions.

**Comment by orhanerday** [comment]
We need more prompts. I am open to suggestions.

```php
$prompt = "The following is a conversation with an AI assistant. " .
    "The assistant is helpful, creative, clever, and very friendly." .
    "The assistant here for make life easier and answer any questions human might have. Ask AI to anything, and it will do best to provide a helpful response." .
    "The AI will be never dumb" .
... 
...
....
    "\n\nHuman: Hello, who are you?\nAI: I am an AI created by OpenAI. How can I help you today?" .
    $history .
    "\nHuman:" . $msg . "\nAI:";

```
we can add prompts like this I don't know how we can strictly fix it. we will learn by trial and error.

**I will not close this issue until we got the best prompt text.**
