### ISSUE TITLE
program doesn't work properly

### ISSUE THREAD

**Issue by kaykay012** [orhanerday/ChatGPT#11]
After I run the program, I get an error:
```
Warning: SQLite3::prepare(): Unable to prepare statement: 1, no such table: chat_history in /home/php/app/api.php on line 12

Fatal error: Uncaught Error: Call to a member function bindValue() on bool in /home/php/app/api.php:13 Stack trace: #0 {main} thrown in /home/php/app/api.php on line 13
```

**Comment by yangliu618** [comment]
You need change ?? to ?: on all php file where use getenv('***') ??
OR set this env on you system

such as:
$open_ai_model = getenv('OPENAI_MODEL') ?: 'gpt-3.5-turbo';
$open_ai_temperature = floatval(getenv('OPENAI_TEMPERATURE') ?: '1.0');
$open_ai_max_tokens = intval(getenv('OPENAI_MAX_TOKENS') ?: '100');
$open_ai_frequency_penalty = floatval(getenv('OPENAI_FREQUENCY_PENALTY') ?: '0.0');
$open_ai_presence_penalty = floatval(getenv('OPENAI_PRESENCE_PENALTY') ?: '0.0');
$db_file = getenv('DB_FILE') ?: 'db.sqlite';

**Comment by orhanerday** [comment]
is `db.sqlite` file exist in your project root?
