### ISSUE TITLE
Any way to make this a website chatbot?

### ISSUE THREAD

**Issue by frishtik** [orhanerday/ChatGPT#12]
Bro this is terrific. By any chance, is it possible to use this chat as a chatbot that appears at the bottom of a website, customer service style? Do you have a hint as of how it might be able to implement it? Thanks anyway, your work is spectacular.

**Comment by orhanerday** [comment]
Thanks for the kind words bro, it means a lot to me.  you can turn the `section` div into a popup on your website. Also, you can join our discord server to get help, check the readme for the invite URL.

Now I am closing the issue.
