### ISSUE TITLE
Help me with davinci

### ISSUE THREAD

**Issue by sparcbr** [orhanerday/ChatGPT#13]
I'm trying to use davinci model, so I replaced model in $opts in event-stream.php:
$opts = [
   'model' => 'davinci', 
  ...
];

but now  I get "Invalid URL (POST \/v1\/chat\/completions)"

Could you point me in the right direction?

What I intend to do? I'd like to train a model with custom questions/answer and then use it in the chat. And I read that  fine-tuning is available only for these models: davinci, curie, babbage, and ada

Thanks

**Comment by orhanerday** [comment]
Please check this version, https://github.com/orhanerday/ChatGPT/releases/tag/1.0

fetch all branches and switch the complete branch
