### ISSUE TITLE
gettign this error

### ISSUE THREAD

**Issue by pks891618** [orhanerday/ChatGPT#17]
This model's maximum context length is 4097 tokens. However, your messages resulted in 192871 tokens. Please reduce the length of the messages.

**Comment by CreateEdward** [comment]
Tokens can be thought of as pieces of words. Before the API processes the prompts, the input is broken down into tokens. You can read the documentation from here. https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them
