### ISSUE TITLE
how to change model

### ISSUE THREAD

**Issue by marvinbudi** [orhanerday/ChatGPT#18]
i want to change to davinci but it not working only gpt-3.5-turbo is working

**Comment by Bamux** [comment]
Take a look at the Open API documentation, where you will see that the responses from the API for davinci have a different structure.
https://platform.openai.com/docs/api-reference/completions

You have to adapt the code in the Javascript file for the other structure, i.e. change it from
let txt = JSON.parse(e.data).choices[0].delta.content; 
to
let txt = JSON.parse(e.data).choices[0].text;

**Comment by orhanerday** [comment]
Thanks Bamux!

**Comment by orhanerday** [comment]
Thanks @Bamux !
