### ISSUE TITLE
EventSource Issue

### ISSUE THREAD

**Issue by srahman-me** [orhanerday/ChatGPT#20]
only the first word of ai response is received and then eventSource stops receiving responses in several servers.

**Comment by orhanerday** [comment]
Please check your internet connection, it should be stable. Also, you can use docker for running the project.

**Comment by srahman-me** [comment]
Hey,

I have found out that this is because of the output_buffer issue of some servers. In some servers ob_flush() has some issue.

Thanks for your attention here.
Best Regards
