### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by TheBlode** [orhanerday/ChatGPT#21]
Hey guys, I've just checked out the repository and I'm really pleased with it. It's great. Just a couple of suggestions from me;

- The chat window isn't auto-scrolling on new messages...so manual scrolling is necessary.
- The code assumes that the codebase sits within the root of our web server. In my case, I needed to update some files in order to make the application work.
- Would be nice to add an input field on startup that checks for the presence of an API key and only then load up the chat interface.
It would be nice to form the code blocks generated by Open AI too.

I don't know if you guys accept PRs but I can certainly provide the code to cover said points in one if you accept those.

All in all, great work on this! Thank you guys.
Martin.

**Comment by orhanerday** [comment]
> I don't know if you guys accept PRs but I can certainly provide the code to cover said points in one if you accept those.

Please do. Nowadays I only fix security issues on the codebase. I don’t have time for feature development.

I appreciate your suggestions.

**Comment by orhanerday** [comment]
If you would like to provide related features, please reopen the issue. Thank you!
