### ISSUE TITLE
Unauthenticated Insecure direct object reference

### ISSUE THREAD

**Issue by devcoinfet** [orhanerday/ChatGPT#22]
On Line 8 of Api.php You are doing the following
$user_id = $_POST['user_id']; -> here there is no authentication check to the api.php endpoint to see if the user is logged in meaning You are suffering from 2 issues here lets start with the first problem  you should authenticate the user before allowing them to make changes.  But that does not stop the problem just restricts to your user base for anyone using this

The core problem here is by accepting the user id from the user and not session variables in the php only that the user does not control, You are allowing any user to just change or delete another users data or chat history

**Comment by orhanerday** [comment]
There is currently no authentication in the app. I added a session feature to manage history, preventing the chat history from being deleted or maybe helping people to giving idea of implementation of their own authentication process.

Thank you for security analyzing the to codebase.
