### ISSUE TITLE
Every time after the question is submitted, the same question and answer will appear when the webpage is refreshed{Sorry, an error occurred, can you ask your question again?}

### ISSUE THREAD

**Issue by jackmamaa** [orhanerday/ChatGPT#3]
Every time I submit a new question, as long as I don’t refresh the page or reopen the page, everything will be fine, otherwise the same question and answer will be repeated => Sorry, an error occurred, can you ask your question again?
Where am I going wrong, is it my cause?

#########################################
[root@ip-172-31-30-218 ~]# sqlite3 --version
3.7.17 2013-05-20 00:56:22 118a3b35693b134d56ebd780123b7fd6f1497668

[root@ip-172-31-30-218 ~]# php --version
PHP 8.1.14 (cli) (built: Jan  9 2023 18:48:38) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.14, Copyright (c), by Zend Technologies`
#########################################

before_refresh:
![before_refresh](https://user-images.githubusercontent.com/119478410/221467123-2793c87a-f7de-4fa7-865d-7364539ae342.png)

after_refresh:
![after_refresh](https://user-images.githubusercontent.com/119478410/221467127-42f77794-e1b2-4fd9-a3da-1fca26892677.png)

**Comment by orhanerday** [comment]
Hit the 'delete chat' button and start conversation.

**Comment by jackmamaa** [comment]
You mean start a new chat? Unfortunately it's still the same problem
It's not like 'reboot will fix everything'

**Comment by orhanerday** [comment]
Did you touch the codes?

**Comment by jackmamaa** [comment]
Pretty much, I just added the environment variable of $open_ai_key
Like this $open_ai_key = $_SERVER['Public_KEY'];

**Comment by jackmamaa** [comment]
Oh, and I specified the model: 'model' => 'text-davinci-003'

**Comment by orhanerday** [comment]
My last suggestion is to use another browser or use in private mode the app. 

If not working maybe you should use another computer/server. I can't set up a docker image because plenty person uses shared hosting.

**Comment by jackmamaa** [comment]
Obviously not a browser issue, I've tried browsers including chrome, edge and its incognito mode.
I am using aws ec2 now.
The stupidest way, now I try to change the environment and version to build the app.🤔😕

**Comment by orhanerday** [comment]
Afaik aws ec2 supports docker, I'll create an image for the app and add it to the readme.

**Comment by orhanerday** [comment]
I added the Dockerfile and edit the readme https://github.com/orhanerday/ChatGPT/commit/afac52d68675921582bdeb14df82f8836589ed83 https://github.com/orhanerday/ChatGPT/commit/094e411669b8734c4ad2dfa465ab4e869ebb60db FYI

**Comment by jackmamaa** [comment]
I run through docker, but unfortunately, the problem persists. I even tested the Android platform.
Here's what I just built: 50.19.189.94:8000

**Comment by orhanerday** [comment]
Sorry, there was a logic error for SQL, please update your project.

https://github.com/orhanerday/ChatGPT/commit/78cd928aec53a401d7935818968e9583dbb6bfcc
