### ISSUE TITLE
Responses from gpt come back empty. Where to dig for fixes?

### ISSUE THREAD

**Issue by androidformax** [orhanerday/ChatGPT#4]
I do not work, I ran everything according to the instructions, composer did not return errors, everything worked fine, the local server is running without errors, api key added his, trying to make any request, returns nothing, where can I find a solution to the problem? [Here's a screenshot](https://skr.sh/i/270223/wXwlyfLf.jpg)

**Comment by orhanerday** [comment]
Please update the project, Fixed with https://github.com/orhanerday/ChatGPT/commit/78cd928aec53a401d7935818968e9583dbb6bfcc

**Comment by androidformax** [comment]
I am update it by git and try by downloading, noticed that now the key must be taken from the .env but it still do not work [ScreenChat](https://skr.sh/i/270223/H5u2GGS3.jpg)
[But now in log the error to which it refers](https://skr.sh/i/270223/QEnLOBJp.jpg)
Just in case, a [screenshot ](https://skr.sh/i/270223/8z3E2Kkc.jpg) of line 57 that I have in this file.
