### ISSUE TITLE
I am update it by git and try by downloading, noticed that now the key must be taken from the .env but it still do not work for me

### ISSUE THREAD

**Issue by androidformax** [orhanerday/ChatGPT#5]
I am update it by git and try by downloading, noticed that now the key must be taken from the .env but it still do not work [ScreenChat](https://skr.sh/i/270223/H5u2GGS3.jpg)
[But now in log the error to which it refers](https://skr.sh/i/270223/QEnLOBJp.jpg)
Just in case, a [screenshot ](https://skr.sh/i/270223/8z3E2Kkc.jpg) of line 57 that I have in this file.

**Comment by orhanerday** [comment]
now you can monitor your error messages from the terminal please update the project. 

execute the command:  pull origin main`


commit https://github.com/orhanerday/ChatGPT/commit/7a608cb783090345b5b7d7049e60dcd3715b4a55
