### ISSUE TITLE
How to extract images from a web page using its URL

### ISSUE THREAD

**Issue by manishkvaish** [orhanerday/ChatGPT#6]
Hi,

First of all, big thanks for such a wonderful collection of codes.

I am really interested to know how I can extract images(image URLs) from a webpage by inputting the web page URL.

Thanks.

**Comment by orhanerday** [comment]
I think it not related with the repo

**Comment by orhanerday** [comment]
Thank you so much about kind words,

Can you ask this question to openAI's official discord?
