### ISSUE TITLE
This issue exists making the chat history meaningless.

### ISSUE THREAD

**Issue by jackmamaa** [orhanerday/ChatGPT#7]
After sqlite3 writes about 20K data (~1.8k token), the event will return an error, the database cannot be updated, and the chat will not have any reply.

But when I manually delete a piece of data with more content, it works again until it "fills up" again.

Like some sort of throttling is being triggered, this issue exists making the chat history meaningless. Can you fix it?🤔

![error](https://user-images.githubusercontent.com/119478410/222908642-c566152f-67b7-47ae-badf-21e14b868228.png)

**Comment by orhanerday** [comment]
I can not generate 20K rows, could you please send your SQLite3 or is it possible for can, you to generate a new one?

and I need steps for error producing

**Comment by jackmamaa** [comment]
Not rows, but the response of the model, which is token. About 18k~20k tokens, the database cannot update the column name: ai the value.
But I try to execute update statement using terminal and it's ok.

**Comment by jackmamaa** [comment]
[18751_Total_token.zip](https://github.com/orhanerday/ChatGPT/files/10894415/18751_Total_token.zip)

This is what I just tested.
step:
1. Completely clear the database table.
2. Tell it to generate ~token for 3k articles.
3. Keep asking questions and generate a total token~19K.
4. I know the question is coming, and finally ask: {Are you OK}. Answer: {null without any reply}. The console issues an error message.

**Comment by jackmamaa** [comment]
Found the problem, the sql query history did not filter the current column name: user_id the value , resulting in submitting all contexts every time.
There is also an option to add some error hints instead of blank output.
like:
Context max token limit.
api error.

**Comment by orhanerday** [comment]
you can get any error from the php serv terminal. 

I am closing the issue.
