### ISSUE TITLE
Chunk

### ISSUE THREAD

**Issue by iraklinish** [orhanerday/ChatGPT#8]
Hello,
I don't want "object":"chat.completion.chunk"
How I can get it on one line?

**Comment by iraklinish** [comment]
> This is not an issue can you please ask this question in our discord server?

I can't :( can you writte here how change it?

**Comment by orhanerday** [comment]
What is '"object":"chat.completion.chunk"'

**Comment by iraklinish** [comment]
In event-stream.php echo $data; returns "object":"chat.completion.chunk" which is why the bot response is returned by chunk

**Comment by iraklinish** [comment]
"How can I assist you" see "content" in every data

data: {"id":"***","object":"chat.completion.chunk","created":***,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" How"},"index":0,"finish_reason":null}]}
data: {"id":"***","object":"chat.completion.chunk","created":***,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" can"},"index":0,"finish_reason":null}]}
data: {"id":"***","object":"chat.completion.chunk","created":***,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" I"},"index":0,"finish_reason":null}]}
data: {"id":"***","object":"chat.completion.chunk","created":***,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" assist"},"index":0,"finish_reason":null}]}
data: {"id":"***","object":"chat.completion.chunk","created":***,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" you"},"index":0,"finish_reason":null}]}

**Comment by orhanerday** [comment]
This is SSE feature you can disable it.

**Comment by iraklinish** [comment]
How?

**Comment by orhanerday** [comment]
Please read https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events


I locked the issue.
