### ISSUE TITLE
Removing text-typing animation?

### ISSUE THREAD

**Issue by TobbyReign** [orhanerday/ChatGPT#9]
Hello, 

I was looking for an alternative (with same algorithm (OpenAI API), as the ChatGPT main live chat website are literally freezing, not able to provide the rest of answer, as "typing effect" they use or i don't know, make the answer not complete. As i see, this app using the same effect, is there a way to just remove the effect ? As it look to be a huge problem for so many peoples (if not all) using chatgpt API, having answer from bot which was cropped for unknown reason (typing animation i guess as i tried another app which was not real time (so, no typing animation), and never ever had uncompleted answer. 

Is there a way to remove typing effect from chatgpt bot ?

thanks

**Comment by orhanerday** [comment]
Hello @TobbyReign,
this is not an issue or enhancement, please ask this question on our discord server.
Please check the readme for the invite URL.

I'll close the issue Thx.
